### ISSUE TITLE
"Level" term in power_test

### ISSUE THREAD

**Issue by gjones1219** [jazznbass/scan-Book#12]
Hi Jurgen! I had one more comment (deeply engaged with use of your package at the moment!), as it relates to the "level" parameter in the scan book. Here you state that the level is: "A list that defines the level increase (effect size d) at the _beginning of each phase_ relative to the previous phase (e.g. list(A = 0, B = 1))." However, shouldn't this say "end"? If the level is the effect of an intervention or experimental manipulation, shouldn't this value assess the impact of the intervention by the end of phase B compared to phase A? I am pretty sure I am understanding this parameter correctly, but just want to confirm this understanding so that you also might clarify this book if needed.

Thanks,
Grant

**Comment by jazznbass** [comment]
Hi Grant,
hmmm. I think it is the beginning. The end of a phase is affected by the trend and slope effects. In a piecewise regression, the effects represent the intercept and slope for each phase. Here, the level effects refer to the axis intercepts. 
Perhaps this can be better phrased. Something like "constant shift in values in a phase". 
I am in the process of rewriting the chapter on contrasts, and will make these points clearer.

Thank you!
Jürgen

**Comment by gjones1219** [comment]
Thanks for your response! Not totally clear on it, however. Is pretty much just that the main take away here that the "level" effect is the power estimate of the intervention effect? I just want to make sure that the _level effect is indeed the effect of the intervention._

Would be great if you can confirm when you can, thanks!

-Grant

**Comment by jazznbass** [comment]
The level effect is one of the two types of intervention effects (besides slope effect). This is correct.
It is an immediate and constant change of the values throughout a phase.
Nevertheless, the values in a phase might also be affected by a trend and a slope effect.
